"""Fixed nullable property in column

Revision ID: db5093db96a8
Revises: 6866e85d5ea5
Create Date: 2026-07-03 05:25:05.040643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5093db96a8'
down_revision = '6866e85d5ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_monitor', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
